"""created user and images table

Revision ID: 5abfa41e3c25
Revises: 8afd859110e4
Create Date: 2021-08-13 12:47:26.430949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abfa41e3c25'
down_revision = '8afd859110e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=False),
    sa.Column('jwt_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.add_column('images', sa.Column('link', sa.String(), nullable=True))
    op.drop_column('images', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('data', sa.BLOB(), nullable=True))
    op.drop_column('images', 'link')
    op.drop_table('users')
    # ### end Alembic commands ###
